name: workflow run 3-1

on:
  workflow_run:
    workflows:
      - workflow run 2
    types:
      - completed


jobs:
  workflow-run-3-1:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: echo
        run: echo "workflow run 3-1"
      - name: branch
        uses: nelonoel/branch-name@v1.0.1
        run: echo ${BRANCH_NAME}