name: workflow run 3-1

on:
  workflow_run:
    workflows:
      - workflow run 2
    types:
      - completed


jobs:
  workflow-run-3-1:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: echo
        run: echo "workflow run 3-1"
      - name: branch
        run: echo ${{ github.ref }}