name: workflow run 1

on:
  push:
    branches:
    - master

jobs:
  workflow-run-1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: echo
        run: echo "workflow run 1"