name: workflow run 3-2

on:
  workflow_run:
    workflows:
      - workflow run 2
    branches:
      - master
    types:
      - completed


jobs:
  workflow-run-3-2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: echo
        run: echo "workflow run 3-2"
      - name: branch
        run: echo ${{ github.ref }}