name: workflow run 3-3

on:
  workflow_run:
    workflows:
      - workflow run 2
    branches:
      - master
    types:
      - completed


jobs:
  workflow-run-3-3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: echo
        run: echo "workflow run 3-3"